server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://financeiro-api.devgiglio.uk;
        proxy_set_header Host financeiro-api.devgiglio.uk;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
